--INSERT INTO Carrera VALUES (9, 'INGENIERIA EN CIENCIAS Y SISTEMAS')

INSERT INTO Curso VALUES (795,'LOGICA DE SISTEMAS')
INSERT INTO Curso VALUES (770,'INTRODUCCIÓN A LA PROGRAMACIÓN Y COMPUTACIÓN 1')

INSERT INTO Curso VALUES (796,'LENGUAJES FORMALES Y DE PROGRAMACIÓN')
INSERT INTO Curso VALUES (771,'INTRODUCCIÓN A LA PROGRAMACIÓN Y COMPUTACIÓN 2')
INSERT INTO Curso VALUES (2025,'PRÁCTICAS INICIALES')

INSERT INTO Curso VALUES (777,'ORGANIZACIÓN DE LENGUAJES Y COMPILADORES 1')
INSERT INTO Curso VALUES (964,'ORGANIZACIÓN COMPUTACIONAL')
INSERT INTO Curso VALUES (772,'ESTRUCTURA DE DATOS')

INSERT INTO Curso VALUES (722,'TEORIA DE SISTEMAS 1')
INSERT INTO Curso VALUES (014,'ECONOMIA')
INSERT INTO Curso VALUES (781,'ORGANIZACIÓN DE LENGUAJES Y COMPILADORES 2')
INSERT INTO Curso VALUES (778,'ARQUITECTURA DE COMPUTADORAS Y ENSAMBLADORES 1')
INSERT INTO Curso VALUES (773,'MANEJO E IMPLEMENTACIÓN DE ARCHIVOS')

INSERT INTO Curso VALUES (724,'TEORIA DE SISTEMAS 2')
INSERT INTO Curso VALUES (281,'SISTEMAS OPERATIVOS 1')
INSERT INTO Curso VALUES (779,'ARQUITECTURA DE COMPUTADORAS Y ENSAMBLADORES 2')
INSERT INTO Curso VALUES (970,'REDES DE COMPUTADORAS 1')
INSERT INTO Curso VALUES (774,'BASES DE DATOS 1')
INSERT INTO Curso VALUES (2036,'PRÁCTICAS INTERMEDIAS')

INSERT INTO Curso VALUES (285,'SISTEMAS OPERATIVOS 2')
INSERT INTO Curso VALUES (975,'REDES DE COMPUTADORAS 2')
INSERT INTO Curso VALUES (775,'BASES DE DATOS 2')
INSERT INTO Curso VALUES (283,'ANÁLISIS Y DISEÑO DE SISTEMAS 1')
INSERT INTO Curso VALUES (797,'SEMINARIO DE SISTEMAS 1')

INSERT INTO Curso VALUES (729,'MODELACION Y SIMULACIÓN 1')
INSERT INTO Curso VALUES (786,'SISTEMAS ORGANIZACIONES Y GERENCIALES 1')
INSERT INTO Curso VALUES (972,'INTELIGENCIA ARTIFICIAL 1')
INSERT INTO Curso VALUES (785,'ANÁLISIS Y DISEÑO DE SISTEMAS 2')
INSERT INTO Curso VALUES (798,'SEMINARIO DE SISTEMAS 2')

INSERT INTO Curso VALUES (787,'GERENCIALES 2')
INSERT INTO Curso VALUES (790,'EMPRENDEDORES DE NEGOCIOS INFORMÁTICOS')
INSERT INTO Curso VALUES (720,'MODELACIÓN Y SIMULACIÓN 2')
INSERT INTO Curso VALUES (780,'SOFTWARE AVANZADO')


--INSERT INTO Curso VALUES ('PROGRAMACIÓN COMERCIAL 1')
--INSERT INTO Curso VALUES (090,'PROGRAMACIÓN DE COMPUTADORAS 1 090')
--INSERT INTO Curso VALUES (090,'PROGRAMACIÓN DE COMPUTADORAS 2')

--select * from curso
--DELETE FROM Curso